#!/bin/sh

apt-get install -y build-essential
apt-get install -y haproxy
apt-get install -y ruby1.9.1 ruby1.9.1-dev rubygems1.9.1
apt-get install -y supervisor

gem install thin sinatra synapse

cp $CONF/app/haproxy /etc/default/haproxy
cp $CONF/app/synapse.conf /etc/synapse.conf
