#!/bin/bash

set -e

apt-get install -y curl

# Add the Docker repository key to your local keychain
# using apt-key finger you can check the fingerprint matches
# 36A1 D786 9245 C895 0F96 6E92 D857 6A8B A88D 21E9
curl https://get.docker.io/gpg | apt-key add -

# Add the Docker repository to your apt sources list.
echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list

apt-get update

# Install, you will see another warning that the package cannot be authenticated.
# Confirm install.
apt-get install -y lxc-docker
