#!/bin/sh

RUNLEVEL=1 apt-get install -y openjdk-7-jdk openjdk-7-jre tomcat7

# Run tomcat on port 80 since Eureka defaults to that port
cp $CONF/eureka/server.xml /etc/tomcat7/server.xml
cp $CONF/eureka/tomcat7 /etc/default/tomcat7
echo 0.0.0.0/32:80 > /etc/authbind/byuid/tomcat7

# Set JVM parameters
mkdir /var/lib/tomcat7/bin
cp $CONF/eureka/setenv.sh /var/lib/tomcat7/bin

cp $SCRIPT_PATH/../eureka.war /var/lib/tomcat7/webapps/eureka.war

service tomcat7 start
